### ISSUE TITLE
Dracula Pythonista Link Not Working

### ISSUE THREAD

**Issue by Geoff12889** [dracula/pythonista#2]
The link on the [Dracula Pythonista page](https://draculatheme.com/pythonista) is not working. Inspecting the element, it shows up as a blank anchor tag. Unable to install the theme on my iDevice.

**Comment by xxps** [comment]
The link is in the [INSTALL.md](https://github.com/dracula/pythonista/blob/master/INSTALL.md), click Raw.

**Comment by Geoff12889** [comment]
~~The link in the INSTALL.md only takes you to the Dracula site (https://draculatheme.com/pythonista) where there is a line of text that says "_On your device, [click on this link](). If Pythonista 3 is installed, it will ask you to open the app. Tap Open to install it._" Clicking the link does not open Pythonista or install the Dracula theme.~~

Disregard my last. I didn't check the RAW like you suggested...
